version: "3"

networks:
  internalnet:
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/16
services:
  ntity-01:
    image: ntity/blockchain
    restart: on-failure
    container_name: ntity-01
    hostname: ntity-01
    volumes:
      - /data/blockchain/ntity-01:/blockchain
      - /data/blockchain/password.txt:/blockchain/password.txt
      - /data/blockchain/static-nodes.json:/blockchain/static-nodes.json
      - /data/blockchain/ntity2020-genesis.json:/blockchain/ntity.genesis.json
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    networks:
      internalnet:
        ipv4_address: 172.21.1.2
    environment:
      - NETWORK_ID=197710212030
      - GETH_OPTS=--unlock=REPLACE YOUR WALLET --nodiscover --miner.gasprice=1 --allow-insecure-unlock --password /blockchain/password.txt --mine --minerthreads=1 --maxpeers=0
      - DATA_DIR=/blockchain
      - FREEZER_DIR=/blockchain/freezer
