version: "3"

networks:
  internalnet:
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/16
services:
  ntity-01:
    image: ntity/blockchain
    restart: on-failure
    container_name: ntity-01
    hostname: ntity-01
    volumes:
      - /data/ethereum/ntity-01:/ethereum
    expose:
      - "8545"
      - "8546"
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    networks:
      internalnet:
        ipv4_address: 172.21.1.2
    environment:
      - NETWORK_ID=197710212030
      - GETH_OPTS=--nodiscover --miner.gasprice=1 --allow-insecure-unlock --unlock=0xbf518cd53a0badf3ce00f78fd268d47fb7cb78c8 --password /ethereum/password.txt --mine --minerthreads=1 --maxpeers=0
