version: "3"

networks:
  internalnet:
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/16
services:
  ntity-01:
    image: ntity/blockchain
    restart: on-failure
    container_name: ntity-01
    hostname: ntity-01
    volumes:
      - /data/blockchain/ntity-01:/blockchain
    expose:
      - "8545"
      - "8546"
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    networks:
      internalnet:
        ipv4_address: 172.21.1.2
    environment:
      - NETWORK_ID=197710212030
      - GETH_OPTS=--nodiscover --miner.gasprice=1 --allow-insecure-unlock --unlock=0xf41f937875d06b2f3c569bde199c6cfd3a64c47c --password /blockchain/password.txt --mine --minerthreads=1 --maxpeers=0
